### ISSUE TITLE
SEM  : FileNotFoundError: [Errno 2] No such file or directory: '/home/aks/IB/new/bake/source/ns-3.36/build/optimized/build-status.p

### ISSUE THREAD

**Issue by BenGitUHA** [signetlabdei/sem#68]
Hello,
I used SEM a year ago, and it works perfectly! However, with Python 3.10, it does not work as expected.
I want to run a simulation about lorawan, so I start by :  sem run --results-dir=./results --ns-3-path=. --script=complete-network-example
However, I get the following error :
/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Building ns-3: 100%|██████████████████████████████████████████████████████████████████████| [06:04<00:00]
Traceback (most recent call last):
  File "/home/aks/IB/new/bake/source/ns-3.36/SEM_IB/Lora_SEM_start3.py", line 16, in <module>
    campaign = sem.CampaignManager.new(ns_path, script, campaign_dir, overwrite=True)
  File "/home/aks/.local/lib/python3.10/site-packages/sem/manager.py", line 157, in new
    runner = CampaignManager.create_runner(ns_path, script,
  File "/home/aks/.local/lib/python3.10/site-packages/sem/manager.py", line 260, in create_runner
    return locals().get(runner_type,
  File "/home/aks/.local/lib/python3.10/site-packages/sem/runner.py", line 78, in __init__
    spec.loader.exec_module(build_status)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/home/aks/IB/new/bake/source/ns-3.36/build/optimized/build-status.py'

Any help ?
Thanks

**Comment by Thecave3** [comment]
This is hard to replicate and looks like an issue due to versions shenanigans
